server {
    listen 80;
    server_name localhost;

    # Preserve host port on redirects
    absolute_redirect off;

    # Serve static assets from root directory
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Enable Gzip compression for fast loading
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml audio/mpeg;
}
